version: "3.9"

services:
  db:
    image: cockroachdb/cockroach:v25.2.5
    command: start-single-node --insecure
    env_file:
      - .env
    ports:
      - "26258:26257"  # SQL port
      - "8081:8080"    # Admin UI
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD-SHELL", "cockroach sql --insecure -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIX_ENV: dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app:rw
      - ./.env:/app/.env:rw
    command: /usr/local/bin/start.sh

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  cockroach_data:
  redis_data:
