apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-deployment.yaml
- redis-deployment.yaml
- mailhog-deployment.yaml
- phoenix-deployment.yaml
- phoenix-uploads-pv.yaml
- phoenix-uploads-pvc.yaml
- phoenix-models-pv.yaml
- phoenix-models-pvc.yaml
- db-init-job.yaml