apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoenix-models-pvc
  namespace: phoenixapp
  labels:
    app: phoenix-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: phoenix-models-local-pv
