apiVersion: v1
kind: Service
metadata:
  name: phoenix-web-headless
  labels:
    app: phoenix-web
spec:
  clusterIP: None
  selector:
    app: phoenix-web
  ports:
  - name: epmd
    port: 4369
    targetPort: 4369
  - name: dist
    port: 9001 # Default distribution port range start
    targetPort: 9001
