apiVersion: v1
kind: PersistentVolume
metadata:
  name: phoenix-models-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # Use Docker VM internal storage for 3D models
    path: /var/lib/k8s-pvs/phoenix-models
    type: DirectoryOrCreate
