apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
  namespace: phoenixapp
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: phoenixapp:prod
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: phoenix-config
            - secretRef:
                name: phoenix-secrets
          command: ["/app/bin/phoenix_app", "eval", "PhoenixApp.Release.migrate()"]
