defmodule PhoenixAppWeb.ConnCase do
  @moduledoc """
  This module defines the test case to be used by
  tests that require setting up a connection.

  Such tests rely on Phoenix.ConnTest and the SQL sandbox
  for isolated DB access.
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      # Import conveniences for testing with connections
      use Phoenix.ConnTest

      alias PhoenixApp.Repo

      import Ecto
      import Ecto.Changeset
      import Ecto.Query

      # Import route helpers (Routes helper is generated by Phoenix)
      import PhoenixAppWeb.Router.Helpers, only: [path: 2, path: 3]

      @endpoint PhoenixAppWeb.Endpoint
    end
  end

  setup tags do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(PhoenixApp.Repo)

    unless tags[:async] do
      Ecto.Adapters.SQL.Sandbox.mode(PhoenixApp.Repo, {:shared, self()})
    end

    {:ok, conn: Phoenix.ConnTest.build_conn()}
  end
end
