apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-config
data:
  MIX_ENV: "dev"
  DB_USERNAME: "postgres"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "phoenixapp_dev"
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/phoenixapp_dev"
  REDIS_URL: "redis://redis:6379/0"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_USER: "ted"
  SMTP_PASS: "nugent"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
  RUST_LOG: "info"
  GAME_SERVICE_PORT: "9000"
  PHOENIX_SERVICE_URL: "http://phoenix-web:4000"
  PHOENIX_HOST: "localhost"