apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phoenixapp-dev

resources:
- ../../base
- namespace.yaml
- configmap.yaml
- secrets.yaml
- ingress.yaml
- mailhog-ingress.yaml

images:
- name: phoenixapp
  newTag: dev

patches:
- path: phoenix-patch.yaml