apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-web
spec:
  template:
    spec:
      containers:
      - name: phoenix
        env:
        - name: MIX_ENV
          value: "dev"
        - name: HCAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: phoenix-secrets
              key: HCAPTCHA_SITE_KEY
        - name: HCAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: phoenix-secrets
              key: HCAPTCHA_SECRET_KEY