apiVersion: v1
kind: Secret
metadata:
  name: mailhog-auth
type: Opaque
data:
  # admin:$2y$10$2b2cu/0iS6TPH.VUeBTTUOugd0doA4H43XSLUBXQBIZbQ5nu19BBG
  # Username: admin, Password: secure123!
  auth: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx