apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: phoenix
        env:
        - name: MIX_ENV
          value: "prod"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"